FROM centos:8
RUN yum -y update && yum -y install gcc python3-devel git && yum -y install python3
LABEL maintainer="Qin Ke<collinsctk@qytang.com>"

ENV RUN_PORT=8000
ENV GIT_URL=https://gitee.com/qytang/docker_djg.git

VOLUME /djg
WORKDIR /djg/
COPY requirement.txt /djg/
RUN pip3 install -i https://pypi.douban.com/simple/ -r requirement.txt && rm -f requirement.txt

# Make ssh dir
RUN mkdir /root/.ssh/

# Copy over private key, and set permissions
ADD /root/.ssh/id_rsa /root/.ssh/id_rsa
RUN chmod 777 /root/.ssh/id_rsa
RUN chown -R root:root /root/.ssh

# Create known_hosts
RUN touch /root/.ssh/known_hosts

RUN ssh-keyscan gitee.com >> /root/.ssh/known_hosts
RUN echo -e "Host gitee.com\n\tStrictHostKeyChecking no\n" >> /etc/ssh/ssh_config
RUN git clone git@gitee.com:qytang/docker_djg.git


WORKDIR /djg/docker_djg/qyt_djg/

EXPOSE $RUN_PORT

CMD python3 manage.py runserver 0.0.0.0:$RUN_PORT